import React, { useState, useEffect } from 'react';
import API from '../api/axiosInstance'; 

const CATEGORY_MAP = {
  "Skincare": {
    subCategories: ["Face Wash", "Face Toner", "Face Serum", "Moisturiser", "Sunscreen"],
    concerns: ["Pigmentation", "Acne", "Ageing", "Sun Protection", "Sensitivity"],
    ingredients: ["Vitamin C", "Salicylic Acid", "Hyaluronic Acid", "Neem", "Rose"]
  },
  "Haircare": {
    subCategories: ["Shampoo", "Conditioner", "Hair Oil", "Hair Serum", "Hair Perfume"],
    concerns: ["Hair Growth", "Hair Fall", "Dandruff", "Dry/Damaged Hair", "Hair Loss"],
    ingredients: ["Rosemary", "Onion", "Coconut", "Argan", "Tea Tree", "Castor"]
  },
  "Bodycare": {
    subCategories: ["Body Wash", "Body Scrub", "Body Lotion", "Body Oil", "Soaps"],
    concerns: ["Body Acne", "Dryness", "Tanning", "Stretch Marks"],
    ingredients: ["Coffee", "Almond", "Shea Butter", "Cocoa", "Lavender"]
  },
  "Gifting": {
    subCategories: [], 
    concerns: [],
    ingredients: []
  }
};

const ProductModal = ({ isOpen, onClose, fetchProducts, productToEdit }) => {
  const defaultState = {
    name: '',
    description: '',
    mrp: '',
    price: '',
    category: 'Skincare',
    subCategory: CATEGORY_MAP['Skincare'].subCategories[0],
    concern: CATEGORY_MAP['Skincare'].concerns[0], 
    keyIngredient: CATEGORY_MAP['Skincare'].ingredients[0],
    countInStock: '', 
    image: '', // Main Image
    images: [], // ✅ NEW: Array for extra gallery images
    sale: false,
    bestSeller: false
  };

  const [formData, setFormData] = useState(defaultState);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (productToEdit) {
      const cat = productToEdit.category && Array.isArray(productToEdit.category) 
        ? productToEdit.category[0] 
        : (productToEdit.category || 'Skincare');
        
      const subCat = productToEdit.category && Array.isArray(productToEdit.category) && productToEdit.category[1] 
        ? productToEdit.category[1] 
        : '';

      let ingredient = '';
      if (productToEdit.keyActives && Array.isArray(productToEdit.keyActives) && productToEdit.keyActives.length > 0) {
        const active = productToEdit.keyActives[0];
        ingredient = typeof active === 'object' ? (active.name || active.title || '') : active;
      }

      setFormData({
        ...productToEdit,
        category: cat,
        subCategory: subCat || (CATEGORY_MAP[cat]?.subCategories[0] || ''),
        concern: productToEdit.concern || (CATEGORY_MAP[cat]?.concerns[0] || ''),
        keyIngredient: ingredient || (CATEGORY_MAP[cat]?.ingredients[0] || ''),
        images: productToEdit.images || [] // ✅ Load existing gallery images
      });
    } else {
      setFormData(defaultState);
    }
    setError('');
  }, [productToEdit, isOpen]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    if (name === 'category') {
      const map = CATEGORY_MAP[value] || { subCategories: [], concerns: [], ingredients: [] };
      setFormData({
        ...formData,
        category: value,
        subCategory: map.subCategories.length > 0 ? map.subCategories[0] : '',
        concern: map.concerns.length > 0 ? map.concerns[0] : '',
        keyIngredient: map.ingredients.length > 0 ? map.ingredients[0] : ''
      });
    } else {
      setFormData({ 
        ...formData, 
        [name]: type === 'checkbox' ? checked : value 
      });
    }
  };

  // ✅ Multi-Image Handlers
  const handleExtraImageChange = (index, value) => {
    const newImages = [...formData.images];
    newImages[index] = value;
    setFormData({ ...formData, images: newImages });
  };

  const addExtraImageField = () => {
    setFormData({ ...formData, images: [...formData.images, ''] });
  };

  const removeExtraImageField = (index) => {
    const newImages = formData.images.filter((_, i) => i !== index);
    setFormData({ ...formData, images: newImages });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    const autoGeneratedId = `PRD-${Date.now()}`;

    const payload = {
      ...formData,
      mrp: parseFloat(formData.mrp),
      price: parseFloat(formData.price),
      countInStock: parseInt(formData.countInStock, 10),
      productId: productToEdit ? (productToEdit.productId || autoGeneratedId) : autoGeneratedId,
      category: [formData.category, formData.subCategory].filter(Boolean),
      keyActives: formData.keyIngredient ? [{ name: formData.keyIngredient }] : [],
      images: formData.images.filter(img => img.trim() !== '') // ✅ Remove any empty string inputs before sending
    };

    try {
      if (productToEdit) {
        const idForUrl = productToEdit.productId || productToEdit._id || productToEdit.id; 
        await API.put(`/product/${idForUrl}`, payload);
      } else {
        await API.post('/product', payload);
      }
      
      fetchProducts();
      onClose();
    } catch (err) {
      console.error("Product Save Error:", err);
      setError(err.response?.data?.message || 'Failed to save product. Check backend requirements.');
    } finally {
      setIsLoading(false);
    }
  };
  
  if (!isOpen) return null;

  const activeMap = CATEGORY_MAP[formData.category] || { subCategories: [], concerns: [], ingredients: [] };
  const noOptions = activeMap.subCategories.length === 0;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[9999] p-4">
      <div className="bg-white rounded-2xl p-6 md:p-8 w-full max-w-2xl shadow-2xl overflow-y-auto max-h-[90vh]">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">
          {productToEdit ? 'Edit Formulation' : 'Add New Formulation'}
        </h2>

        {error && <div className="mb-6 p-4 bg-red-50 text-red-700 rounded-xl text-sm font-semibold border border-red-100">{error}</div>}

        <form onSubmit={handleSubmit} className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Product Name</label>
              <input
                type="text" name="name" required value={formData.name} onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-slate-900 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Main Image URL</label>
              <input
                type="url" name="image" required value={formData.image} onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-slate-900 outline-none"
              />
            </div>
          </div>

          {/* ✅ Multi-Image Input Section */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
            <label className="block text-sm font-semibold text-gray-700 mb-2">Gallery Images (Optional Side Thumbnails)</label>
            {formData.images.map((url, index) => (
              <div key={index} className="flex gap-2 mb-2">
                <input
                  type="url"
                  value={url}
                  onChange={(e) => handleExtraImageChange(index, e.target.value)}
                  placeholder="https://example.com/gallery-image.jpg"
                  className="w-full border border-gray-300 rounded-lg p-2 text-sm focus:ring-2 focus:ring-slate-900 outline-none"
                />
                <button 
                  type="button" 
                  onClick={() => removeExtraImageField(index)}
                  className="px-3 bg-red-100 text-red-600 rounded-lg hover:bg-red-200 font-bold transition-colors"
                  title="Remove Image"
                >
                  X
                </button>
              </div>
            ))}
            <button 
              type="button" 
              onClick={addExtraImageField}
              className="text-sm font-bold text-indigo-600 hover:text-indigo-800 transition-colors mt-1 flex items-center gap-1"
            >
              + Add Gallery Image
            </button>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Description</label>
            <textarea
              name="description" required value={formData.description} onChange={handleChange} rows="3"
              className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-slate-900 outline-none"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">MRP (₹)</label>
              <input
                type="number" step="0.01" name="mrp" required value={formData.mrp} onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-slate-900 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Selling Price (₹)</label>
              <input
                type="number" step="0.01" name="price" required value={formData.price} onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-slate-900 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Available Stock</label>
              <input
                type="number" name="countInStock" required value={formData.countInStock} onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-slate-900 outline-none"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 p-4 bg-gray-50 rounded-xl border border-gray-100">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Main Category</label>
              <select name="category" value={formData.category} onChange={handleChange} className="w-full border border-gray-300 rounded-lg p-2.5 outline-none bg-white font-medium">
                {Object.keys(CATEGORY_MAP).map(cat => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${noOptions ? 'text-gray-400' : 'text-gray-700'}`}>
                Product Type
              </label>
              <select name="subCategory" value={formData.subCategory} onChange={handleChange} disabled={noOptions}
                className="w-full border border-gray-300 rounded-lg p-2.5 outline-none bg-white disabled:bg-gray-100 disabled:text-gray-400 transition-colors">
                {noOptions ? <option value="">N/A</option> : activeMap.subCategories.map(item => <option key={item} value={item}>{item}</option>)}
              </select>
            </div>
            
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${noOptions ? 'text-gray-400' : 'text-gray-700'}`}>
                Primary Concern
              </label>
              <select name="concern" value={formData.concern} onChange={handleChange} disabled={noOptions}
                className="w-full border border-gray-300 rounded-lg p-2.5 outline-none bg-white disabled:bg-gray-100 disabled:text-gray-400 transition-colors">
                {noOptions ? <option value="">N/A</option> : activeMap.concerns.map(item => <option key={item} value={item}>{item}</option>)}
              </select>
            </div>

            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${noOptions ? 'text-gray-400' : 'text-gray-700'}`}>
                Key Ingredient
              </label>
              <select name="keyIngredient" value={formData.keyIngredient} onChange={handleChange} disabled={noOptions}
                className="w-full border border-gray-300 rounded-lg p-2.5 outline-none bg-white disabled:bg-gray-100 disabled:text-gray-400 transition-colors">
                {noOptions ? <option value="">N/A</option> : activeMap.ingredients.map(item => <option key={item} value={item}>{item}</option>)}
              </select>
            </div>
          </div>

          <div className="flex items-center gap-3 py-2">
            <input
              type="checkbox" id="sale" name="sale"
              checked={formData.sale} onChange={handleChange}
              className="w-5 h-5 text-slate-900 rounded focus:ring-slate-900 cursor-pointer"
            />
            <label htmlFor="sale" className="text-sm font-bold text-gray-700 cursor-pointer">
              Mark as "On Sale" (Shows sale badge on storefront)
            </label>
          </div>

          <div className="flex justify-end gap-3 mt-8 pt-4 border-t border-gray-100">
            <button type="button" onClick={onClose} disabled={isLoading} className="px-6 py-2.5 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 font-bold transition-colors">
              Cancel
            </button>
            <button type="submit" disabled={isLoading} className="px-8 py-2.5 bg-slate-900 text-white rounded-lg hover:bg-slate-800 shadow-md font-bold transition-all">
              {isLoading ? 'Saving...' : (productToEdit ? 'Update Details' : 'Publish Product')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ProductModal;